// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.29.3
// source: data_3.proto

package data_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataThreeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	One int64 `protobuf:"varint,1,opt,name=one,proto3" json:"one,omitempty"`
	Two int64 `protobuf:"varint,2,opt,name=two,proto3" json:"two,omitempty"`
}

func (x *DataThreeRequest) Reset() {
	*x = DataThreeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_3_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataThreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataThreeRequest) ProtoMessage() {}

func (x *DataThreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_3_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataThreeRequest.ProtoReflect.Descriptor instead.
func (*DataThreeRequest) Descriptor() ([]byte, []int) {
	return file_data_3_proto_rawDescGZIP(), []int{0}
}

func (x *DataThreeRequest) GetOne() int64 {
	if x != nil {
		return x.One
	}
	return 0
}

func (x *DataThreeRequest) GetTwo() int64 {
	if x != nil {
		return x.Two
	}
	return 0
}

type DataThreeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	One int64 `protobuf:"varint,1,opt,name=one,proto3" json:"one,omitempty"`
	Two int64 `protobuf:"varint,2,opt,name=two,proto3" json:"two,omitempty"`
}

func (x *DataThreeResponse) Reset() {
	*x = DataThreeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_3_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataThreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataThreeResponse) ProtoMessage() {}

func (x *DataThreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_3_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataThreeResponse.ProtoReflect.Descriptor instead.
func (*DataThreeResponse) Descriptor() ([]byte, []int) {
	return file_data_3_proto_rawDescGZIP(), []int{1}
}

func (x *DataThreeResponse) GetOne() int64 {
	if x != nil {
		return x.One
	}
	return 0
}

func (x *DataThreeResponse) GetTwo() int64 {
	if x != nil {
		return x.Two
	}
	return 0
}

var File_data_3_proto protoreflect.FileDescriptor

var file_data_3_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x33, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a,
	0x64, 0x61, 0x74, 0x61, 0x2e, 0x74, 0x68, 0x72, 0x65, 0x65, 0x22, 0x36, 0x0a, 0x10, 0x44, 0x61,
	0x74, 0x61, 0x54, 0x68, 0x72, 0x65, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6f, 0x6e, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x74, 0x77, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x74,
	0x77, 0x6f, 0x22, 0x37, 0x0a, 0x11, 0x44, 0x61, 0x74, 0x61, 0x54, 0x68, 0x72, 0x65, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x6e, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6f, 0x6e, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x77, 0x6f,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x74, 0x77, 0x6f, 0x42, 0x43, 0x5a, 0x41, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x44, 0x6f, 0x6b, 0x74, 0x6f, 0x72,
	0x47, 0x68, 0x6f, 0x73, 0x74, 0x2f, 0x72, 0x65, 0x66, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x2f, 0x73, 0x72, 0x63, 0x2f, 0x67, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63,
	0x2f, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x76, 0x31, 0x3b, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x76, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_data_3_proto_rawDescOnce sync.Once
	file_data_3_proto_rawDescData = file_data_3_proto_rawDesc
)

func file_data_3_proto_rawDescGZIP() []byte {
	file_data_3_proto_rawDescOnce.Do(func() {
		file_data_3_proto_rawDescData = protoimpl.X.CompressGZIP(file_data_3_proto_rawDescData)
	})
	return file_data_3_proto_rawDescData
}

var file_data_3_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_data_3_proto_goTypes = []interface{}{
	(*DataThreeRequest)(nil),  // 0: data.three.DataThreeRequest
	(*DataThreeResponse)(nil), // 1: data.three.DataThreeResponse
}
var file_data_3_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_data_3_proto_init() }
func file_data_3_proto_init() {
	if File_data_3_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_data_3_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataThreeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_3_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataThreeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_data_3_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_data_3_proto_goTypes,
		DependencyIndexes: file_data_3_proto_depIdxs,
		MessageInfos:      file_data_3_proto_msgTypes,
	}.Build()
	File_data_3_proto = out.File
	file_data_3_proto_rawDesc = nil
	file_data_3_proto_goTypes = nil
	file_data_3_proto_depIdxs = nil
}
